name: Auto Build and Push Images

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggering

# Add explicit permissions block
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: mollomm1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu
            version: "24.04"
          - distro: ubuntu
            version: "22.04"
          - distro: debian
            version: "12"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version
        id: version
        run: |
          for version in ${{ join(matrix.distro.versions, ' ') }}; do
            echo "version=${version}" >> $GITHUB_OUTPUT
            break
          done

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ matrix.distro }}/${{ matrix.version }}/base
          file: ./images/${{ matrix.distro }}/${{ matrix.version }}/base/Dockerfile
          build-args: |
            VERSION=${{ matrix.version }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.distro }}-${{ matrix.version }}-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push base-app image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ matrix.distro }}/${{ matrix.version }}/base-app
          file: ./images/${{ matrix.distro }}/${{ matrix.version }}/base-app/Dockerfile
          build-args: |
            VERSION=${{ matrix.version }}
            BASE_IMAGE=${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.distro }}-${{ matrix.version }}-base:latest
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ matrix.distro }}-${{ matrix.version }}-base-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max